2025-08-19T16:14:22.0172491Z ##[group]Run echo "::group::postgres container logs"
2025-08-19T16:14:22.0172880Z [36;1mecho "::group::postgres container logs"[0m
2025-08-19T16:14:22.0173349Z [36;1mdocker logs b8676ee6dd289d8466fcab23d7886fd40ecf15790e01bc8c8b0cdee831eefa5a --tail 200[0m
2025-08-19T16:14:22.0173801Z [36;1mecho "::endgroup::"[0m
2025-08-19T16:14:22.0213795Z shell: /usr/bin/bash -e {0}
2025-08-19T16:14:22.0214040Z env:
2025-08-19T16:14:22.0214245Z   REDIS_URL: redis://localhost:6379/0
2025-08-19T16:14:22.0214509Z   RATE_LIMIT_DEFAULT: 100/minute
2025-08-19T16:14:22.0214838Z   TRUST_X_FORWARDED: 1
2025-08-19T16:14:22.0215042Z   PG_USER: postgres
2025-08-19T16:14:22.0215232Z   PG_PASSWORD: pass
2025-08-19T16:14:22.0215422Z   PG_DATABASE: awa
2025-08-19T16:14:22.0215606Z   PG_HOST: localhost
2025-08-19T16:14:22.0215790Z   PG_PORT: 5432
2025-08-19T16:14:22.0216185Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-19T16:14:22.0216580Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-19T16:14:22.0216959Z   DATABASE_URL: ***localhost:5432/awa
2025-08-19T16:14:22.0217229Z   DATA_DIR: /tmp/awa-data
2025-08-19T16:14:22.0217436Z   ENABLE_LIVE: 0
2025-08-19T16:14:22.0217615Z   TESTING: 1
2025-08-19T16:14:22.0217857Z   pythonLocation: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-19T16:14:22.0218257Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.11/x64/lib/pkgconfig
2025-08-19T16:14:22.0218645Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-19T16:14:22.0219003Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-19T16:14:22.0219352Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-19T16:14:22.0219709Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.11/x64/lib
2025-08-19T16:14:22.0220005Z ##[endgroup]
2025-08-19T16:14:22.0280070Z ##[group]postgres container logs
2025-08-19T16:14:22.0403883Z The files belonging to this database system will be owned by user "postgres".
2025-08-19T16:14:22.0405288Z initdb: warning: enabling "trust" authentication for local connections
2025-08-19T16:14:22.0406439Z initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
2025-08-19T16:14:22.0407529Z 2025-08-19 16:11:46.181 UTC [1] LOG:  starting PostgreSQL 15.14 (Debian 15.14-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
2025-08-19T16:14:22.0408301Z 2025-08-19 16:11:46.181 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-08-19T16:14:22.0409188Z 2025-08-19 16:11:46.181 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2025-08-19T16:14:22.0409792Z 2025-08-19 16:11:46.183 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-08-19T16:14:22.0410430Z 2025-08-19 16:11:46.186 UTC [64] LOG:  database system was shut down at 2025-08-19 16:11:46 UTC
2025-08-19T16:14:22.0410996Z 2025-08-19 16:11:46.191 UTC [1] LOG:  database system is ready to accept connections
2025-08-19T16:14:22.0411659Z 2025-08-19 16:13:47.799 UTC [275] ERROR:  column "marketplace" of relation "fees_raw" does not exist at character 34
2025-08-19T16:14:22.0412189Z 2025-08-19 16:13:47.799 UTC [275] STATEMENT:  
2025-08-19T16:14:22.0412687Z 	    INSERT INTO fees_raw (asin, marketplace, fee_type, amount, currency, source, effective_date)
2025-08-19T16:14:22.0413188Z 	    VALUES ($1, $2, $3, $4, $5, $6, $7), ($8, $9, $10, $11, $12, $13, $14)
2025-08-19T16:14:22.0413579Z 	    ON CONFLICT (asin, marketplace, fee_type) DO NOTHING;
2025-08-19T16:14:22.0413869Z 	    
2025-08-19T16:14:22.0414129Z This user must also own the server process.
2025-08-19T16:14:22.0414322Z 
2025-08-19T16:14:22.0414574Z The database cluster will be initialized with locale "en_US.utf8".
2025-08-19T16:14:22.0415372Z The default database encoding has accordingly been set to "UTF8".
2025-08-19T16:14:22.0415851Z The default text search configuration will be set to "english".
2025-08-19T16:14:22.0416247Z 
2025-08-19T16:14:22.0416389Z Data page checksums are disabled.
2025-08-19T16:14:22.0416560Z 
2025-08-19T16:14:22.0417377Z fixing permissions on existing directory /var/lib/postgresql/data ... ok
2025-08-19T16:14:22.0417836Z creating subdirectories ... ok
2025-08-19T16:14:22.0418215Z selecting dynamic shared memory implementation ... posix
2025-08-19T16:14:22.0418591Z selecting default max_connections ... 100
2025-08-19T16:14:22.0418918Z selecting default shared_buffers ... 128MB
2025-08-19T16:14:22.0419326Z selecting default time zone ... Etc/UTC
2025-08-19T16:14:22.0420076Z creating configuration files ... ok
2025-08-19T16:14:22.0420599Z running bootstrap script ... ok
2025-08-19T16:14:22.0421187Z performing post-bootstrap initialization ... ok
2025-08-19T16:14:22.0421522Z syncing data to disk ... ok
2025-08-19T16:14:22.0421673Z 
2025-08-19T16:14:22.0421681Z 
2025-08-19T16:14:22.0421874Z Success. You can now start the database server using:
2025-08-19T16:14:22.0422095Z 
2025-08-19T16:14:22.0422265Z     pg_ctl -D /var/lib/postgresql/data -l logfile start
2025-08-19T16:14:22.0422484Z 
2025-08-19T16:14:22.0423179Z waiting for server to start....2025-08-19 16:11:45.838 UTC [48] LOG:  starting PostgreSQL 15.14 (Debian 15.14-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
2025-08-19T16:14:22.0424075Z 2025-08-19 16:11:45.839 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-08-19T16:14:22.0424924Z 2025-08-19 16:11:45.842 UTC [51] LOG:  database system was shut down at 2025-08-19 16:11:45 UTC
2025-08-19T16:14:22.0425517Z 2025-08-19 16:11:45.845 UTC [48] LOG:  database system is ready to accept connections
2025-08-19T16:14:22.0425856Z  done
2025-08-19T16:14:22.0426029Z server started
2025-08-19T16:14:22.0426219Z CREATE DATABASE
2025-08-19T16:14:22.0426330Z 
2025-08-19T16:14:22.0426336Z 
2025-08-19T16:14:22.0426647Z /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
2025-08-19T16:14:22.0426957Z 
2025-08-19T16:14:22.0427193Z 2025-08-19 16:11:46.057 UTC [48] LOG:  received fast shutdown request
2025-08-19T16:14:22.0427771Z waiting for server to shut down....2025-08-19 16:11:46.058 UTC [48] LOG:  aborting any active transactions
2025-08-19T16:14:22.0428504Z 2025-08-19 16:11:46.060 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
2025-08-19T16:14:22.0429048Z 2025-08-19 16:11:46.062 UTC [49] LOG:  shutting down
2025-08-19T16:14:22.0429498Z 2025-08-19 16:11:46.062 UTC [49] LOG:  checkpoint starting: shutdown immediate
2025-08-19T16:14:22.0430774Z 2025-08-19 16:11:46.085 UTC [49] LOG:  checkpoint complete: wrote 922 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.019 s, sync=0.002 s, total=0.024 s; sync files=301, longest=0.001 s, average=0.001 s; distance=4239 kB, estimate=4239 kB
2025-08-19T16:14:22.0431682Z 2025-08-19 16:11:46.093 UTC [48] LOG:  database system is shut down
2025-08-19T16:14:22.0431981Z  done
2025-08-19T16:14:22.0432149Z server stopped
2025-08-19T16:14:22.0432266Z 
2025-08-19T16:14:22.0432466Z PostgreSQL init process complete; ready for start up.
2025-08-19T16:14:22.0432693Z 
2025-08-19T16:14:22.0433023Z ##[endgroup]
