2025-08-17T19:38:56.7498804Z ##[group]Run echo "::group::postgres container logs"
2025-08-17T19:38:56.7499201Z [36;1mecho "::group::postgres container logs"[0m
2025-08-17T19:38:56.7499684Z [36;1mdocker logs fc1c269c31469b365e38e3ab6ce191efb2b257015d0ddda917ef158cbc9c9fe5 --tail 200[0m
2025-08-17T19:38:56.7500140Z [36;1mecho "::endgroup::"[0m
2025-08-17T19:38:56.7540990Z shell: /usr/bin/bash -e {0}
2025-08-17T19:38:56.7541231Z env:
2025-08-17T19:38:56.7541402Z   PG_USER: postgres
2025-08-17T19:38:56.7541605Z   PG_PASSWORD: pass
2025-08-17T19:38:56.7541789Z   PG_DATABASE: awa
2025-08-17T19:38:56.7541975Z   PG_HOST: localhost
2025-08-17T19:38:56.7542164Z   PG_PORT: 5432
2025-08-17T19:38:56.7542584Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-17T19:38:56.7543004Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-17T19:38:56.7543395Z   DATABASE_URL: ***localhost:5432/awa
2025-08-17T19:38:56.7543637Z   DATA_DIR: /tmp/awa-data
2025-08-17T19:38:56.7543844Z   ENABLE_LIVE: 0
2025-08-17T19:38:56.7544016Z   TESTING: 1
2025-08-17T19:38:56.7544295Z   pythonLocation: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-17T19:38:56.7544696Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.11/x64/lib/pkgconfig
2025-08-17T19:38:56.7545116Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-17T19:38:56.7545476Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-17T19:38:56.7546032Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-17T19:38:56.7546394Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.11/x64/lib
2025-08-17T19:38:56.7546692Z ##[endgroup]
2025-08-17T19:38:56.7605110Z ##[group]postgres container logs
2025-08-17T19:38:56.7722125Z The files belonging to this database system will be owned by user "postgres".
2025-08-17T19:38:56.7723260Z initdb: warning: enabling "trust" authentication for local connections
2025-08-17T19:38:56.7724718Z initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
2025-08-17T19:38:56.7725869Z This user must also own the server process.
2025-08-17T19:38:56.7726227Z 
2025-08-17T19:38:56.7726684Z The database cluster will be initialized with locale "en_US.utf8".
2025-08-17T19:38:56.7727577Z The default database encoding has accordingly been set to "UTF8".
2025-08-17T19:38:56.7728439Z The default text search configuration will be set to "english".
2025-08-17T19:38:56.7728875Z 
2025-08-17T19:38:56.7729119Z Data page checksums are disabled.
2025-08-17T19:38:56.7729402Z 
2025-08-17T19:38:56.7729896Z fixing permissions on existing directory /var/lib/postgresql/data ... ok
2025-08-17T19:38:56.7730624Z creating subdirectories ... ok
2025-08-17T19:38:56.7731473Z selecting dynamic shared memory implementation ... posix
2025-08-17T19:38:56.7732146Z selecting default max_connections ... 100
2025-08-17T19:38:56.7732726Z selecting default shared_buffers ... 128MB
2025-08-17T19:38:56.7733278Z selecting default time zone ... Etc/UTC
2025-08-17T19:38:56.7733816Z creating configuration files ... ok
2025-08-17T19:38:56.7734339Z running bootstrap script ... ok
2025-08-17T19:38:56.7734912Z performing post-bootstrap initialization ... ok
2025-08-17T19:38:56.7735452Z syncing data to disk ... ok
2025-08-17T19:38:56.7735704Z 
2025-08-17T19:38:56.7735715Z 
2025-08-17T19:38:56.7736052Z Success. You can now start the database server using:
2025-08-17T19:38:56.7736441Z 
2025-08-17T19:38:56.7736721Z     pg_ctl -D /var/lib/postgresql/data -l logfile start
2025-08-17T19:38:56.7737096Z 
2025-08-17T19:38:56.7738339Z waiting for server to start....2025-08-17 19:37:31.938 UTC [49] LOG:  starting PostgreSQL 15.14 (Debian 15.14-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
2025-08-17T19:38:56.7739894Z 2025-08-17 19:37:31.939 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-08-17T19:38:56.7741642Z 2025-08-17 19:37:32.241 UTC [1] LOG:  starting PostgreSQL 15.14 (Debian 15.14-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
2025-08-17T19:38:56.7743251Z 2025-08-17 19:37:32.241 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-08-17T19:38:56.7744355Z 2025-08-17 19:37:32.241 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2025-08-17T19:38:56.7745085Z 2025-08-17 19:37:32.242 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-08-17T19:38:56.7745741Z 2025-08-17 19:37:32.245 UTC [65] LOG:  database system was shut down at 2025-08-17 19:37:32 UTC
2025-08-17T19:38:56.7746308Z 2025-08-17 19:37:32.249 UTC [1] LOG:  database system is ready to accept connections
2025-08-17T19:38:56.7746815Z 2025-08-17 19:38:56.668 UTC [201] ERROR:  column "reimb_id" does not exist
2025-08-17T19:38:56.7747583Z 2025-08-17 19:38:56.668 UTC [201] CONTEXT:  SQL statement "CREATE UNIQUE INDEX uq_reimbursements_raw_reimb_id ON reimbursements_raw(reimb_id)"
2025-08-17T19:38:56.7748226Z 	PL/pgSQL function inline_code_block line 5 at SQL statement
2025-08-17T19:38:56.7748625Z 2025-08-17 19:38:56.668 UTC [201] STATEMENT:  
2025-08-17T19:38:56.7748895Z 	        DO $$ BEGIN
2025-08-17T19:38:56.7749104Z 	            IF NOT EXISTS (
2025-08-17T19:38:56.7749576Z 	                SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='uq_reimbursements_raw_reimb_id'
2025-08-17T19:38:56.7750007Z 	            ) THEN
2025-08-17T19:38:56.7750597Z 	                CREATE UNIQUE INDEX uq_reimbursements_raw_reimb_id ON reimbursements_raw(reimb_id);
2025-08-17T19:38:56.7751237Z 	            END IF;
2025-08-17T19:38:56.7751435Z 	        END $$;
2025-08-17T19:38:56.7751613Z 	        
2025-08-17T19:38:56.7752031Z 2025-08-17 19:37:31.942 UTC [52] LOG:  database system was shut down at 2025-08-17 19:37:31 UTC
2025-08-17T19:38:56.7752593Z 2025-08-17 19:37:31.946 UTC [49] LOG:  database system is ready to accept connections
2025-08-17T19:38:56.7752926Z  done
2025-08-17T19:38:56.7753096Z server started
2025-08-17T19:38:56.7753277Z CREATE DATABASE
2025-08-17T19:38:56.7753386Z 
2025-08-17T19:38:56.7753395Z 
2025-08-17T19:38:56.7753706Z /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
2025-08-17T19:38:56.7754023Z 
2025-08-17T19:38:56.7754263Z 2025-08-17 19:37:32.122 UTC [49] LOG:  received fast shutdown request
2025-08-17T19:38:56.7754847Z waiting for server to shut down....2025-08-17 19:37:32.123 UTC [49] LOG:  aborting any active transactions
2025-08-17T19:38:56.7755592Z 2025-08-17 19:37:32.124 UTC [49] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
2025-08-17T19:38:56.7756132Z 2025-08-17 19:37:32.125 UTC [50] LOG:  shutting down
2025-08-17T19:38:56.7756573Z 2025-08-17 19:37:32.125 UTC [50] LOG:  checkpoint starting: shutdown immediate
2025-08-17T19:38:56.7757683Z 2025-08-17 19:37:32.140 UTC [50] LOG:  checkpoint complete: wrote 922 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.013 s, sync=0.002 s, total=0.016 s; sync files=301, longest=0.001 s, average=0.001 s; distance=4239 kB, estimate=4239 kB
2025-08-17T19:38:56.7758581Z 2025-08-17 19:37:32.146 UTC [49] LOG:  database system is shut down
2025-08-17T19:38:56.7758884Z  done
2025-08-17T19:38:56.7759050Z server stopped
2025-08-17T19:38:56.7759164Z 
2025-08-17T19:38:56.7759355Z PostgreSQL init process complete; ready for start up.
2025-08-17T19:38:56.7759579Z 
2025-08-17T19:38:56.7759826Z ##[endgroup]
