2025-08-19T16:07:48.8008700Z ##[group]Run echo "::group::postgres container logs"
2025-08-19T16:07:48.8009074Z [36;1mecho "::group::postgres container logs"[0m
2025-08-19T16:07:48.8009525Z [36;1mdocker logs fc60e495f00e0ec038e916dd1ba30095e32694508d3a4616276ca284c71a889e --tail 200[0m
2025-08-19T16:07:48.8009959Z [36;1mecho "::endgroup::"[0m
2025-08-19T16:07:48.8051324Z shell: /usr/bin/bash -e {0}
2025-08-19T16:07:48.8051573Z env:
2025-08-19T16:07:48.8051781Z   REDIS_URL: redis://localhost:6379/0
2025-08-19T16:07:48.8052050Z   RATE_LIMIT_DEFAULT: 100/minute
2025-08-19T16:07:48.8052274Z   TRUST_X_FORWARDED: 1
2025-08-19T16:07:48.8052470Z   PG_USER: postgres
2025-08-19T16:07:48.8052770Z   PG_PASSWORD: pass
2025-08-19T16:07:48.8052960Z   PG_DATABASE: awa
2025-08-19T16:07:48.8053142Z   PG_HOST: localhost
2025-08-19T16:07:48.8053324Z   PG_PORT: 5432
2025-08-19T16:07:48.8053726Z   PG_SYNC_DSN: ***localhost:5432/awa
2025-08-19T16:07:48.8054130Z   PG_ASYNC_DSN: ***localhost:5432/awa
2025-08-19T16:07:48.8054503Z   DATABASE_URL: ***localhost:5432/awa
2025-08-19T16:07:48.8054763Z   DATA_DIR: /tmp/awa-data
2025-08-19T16:07:48.8054967Z   ENABLE_LIVE: 0
2025-08-19T16:07:48.8055149Z   TESTING: 1
2025-08-19T16:07:48.8055388Z   pythonLocation: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-19T16:07:48.8055784Z   PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.11/x64/lib/pkgconfig
2025-08-19T16:07:48.8056161Z   Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-19T16:07:48.8056683Z   Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-19T16:07:48.8057031Z   Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.11/x64
2025-08-19T16:07:48.8057383Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.11/x64/lib
2025-08-19T16:07:48.8057672Z ##[endgroup]
2025-08-19T16:07:48.8116121Z ##[group]postgres container logs
2025-08-19T16:07:48.8231591Z The files belonging to this database system will be owned by user "postgres".
2025-08-19T16:07:48.8232461Z This user must also own the server process.
2025-08-19T16:07:48.8232951Z 
2025-08-19T16:07:48.8233431Z The database cluster will be initialized with locale "en_US.utf8".
2025-08-19T16:07:48.8234282Z The default database encoding has accordingly been set to "UTF8".
2025-08-19T16:07:48.8235088Z The default text search configuration will be set to "english".
2025-08-19T16:07:48.8235502Z 
2025-08-19T16:07:48.8235730Z Data page checksums are disabled.
2025-08-19T16:07:48.8236025Z 
2025-08-19T16:07:48.8236484Z fixing permissions on existing directory /var/lib/postgresql/data ... ok
2025-08-19T16:07:48.8237092Z creating subdirectories ... ok
2025-08-19T16:07:48.8237486Z selecting dynamic shared memory implementation ... posix
2025-08-19T16:07:48.8237874Z selecting default max_connections ... 100
2025-08-19T16:07:48.8238201Z selecting default shared_buffers ... 128MB
2025-08-19T16:07:48.8238512Z selecting default time zone ... Etc/UTC
2025-08-19T16:07:48.8238812Z creating configuration files ... ok
2025-08-19T16:07:48.8239102Z running bootstrap script ... ok
2025-08-19T16:07:48.8239427Z performing post-bootstrap initialization ... ok
2025-08-19T16:07:48.8239958Z initdb: warning: enabling "trust" authentication for local connections
2025-08-19T16:07:48.8240753Z initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
2025-08-19T16:07:48.8241752Z 2025-08-19 16:05:11.957 UTC [1] LOG:  starting PostgreSQL 15.14 (Debian 15.14-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
2025-08-19T16:07:48.8242472Z 2025-08-19 16:05:11.957 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-08-19T16:07:48.8243251Z 2025-08-19 16:05:11.957 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2025-08-19T16:07:48.8243816Z 2025-08-19 16:05:11.959 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-08-19T16:07:48.8244416Z 2025-08-19 16:05:11.962 UTC [64] LOG:  database system was shut down at 2025-08-19 16:05:11 UTC
2025-08-19T16:07:48.8244954Z 2025-08-19 16:05:11.966 UTC [1] LOG:  database system is ready to accept connections
2025-08-19T16:07:48.8245898Z 2025-08-19 16:07:14.617 UTC [274] ERROR:  column "marketplace" of relation "fees_raw" does not exist at character 34
2025-08-19T16:07:48.8246395Z 2025-08-19 16:07:14.617 UTC [274] STATEMENT:  
2025-08-19T16:07:48.8247183Z 	    INSERT INTO fees_raw (asin, marketplace, fee_type, amount, currency, source, effective_date)
2025-08-19T16:07:48.8248054Z 	    VALUES ($1, $2, $3, $4, $5, $6, $7), ($8, $9, $10, $11, $12, $13, $14)
2025-08-19T16:07:48.8248684Z 	    ON CONFLICT (asin, marketplace, fee_type) DO NOTHING;
2025-08-19T16:07:48.8249162Z 	    
2025-08-19T16:07:48.8249488Z syncing data to disk ... ok
2025-08-19T16:07:48.8249730Z 
2025-08-19T16:07:48.8249743Z 
2025-08-19T16:07:48.8250071Z Success. You can now start the database server using:
2025-08-19T16:07:48.8250433Z 
2025-08-19T16:07:48.8250870Z     pg_ctl -D /var/lib/postgresql/data -l logfile start
2025-08-19T16:07:48.8251220Z 
2025-08-19T16:07:48.8252102Z waiting for server to start....2025-08-19 16:05:11.653 UTC [48] LOG:  starting PostgreSQL 15.14 (Debian 15.14-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit
2025-08-19T16:07:48.8253173Z 2025-08-19 16:05:11.653 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-08-19T16:07:48.8253800Z 2025-08-19 16:05:11.656 UTC [51] LOG:  database system was shut down at 2025-08-19 16:05:11 UTC
2025-08-19T16:07:48.8254630Z 2025-08-19 16:05:11.659 UTC [48] LOG:  database system is ready to accept connections
2025-08-19T16:07:48.8254963Z  done
2025-08-19T16:07:48.8255129Z server started
2025-08-19T16:07:48.8255305Z CREATE DATABASE
2025-08-19T16:07:48.8255419Z 
2025-08-19T16:07:48.8255425Z 
2025-08-19T16:07:48.8255722Z /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
2025-08-19T16:07:48.8256030Z 
2025-08-19T16:07:48.8256250Z 2025-08-19 16:05:11.838 UTC [48] LOG:  received fast shutdown request
2025-08-19T16:07:48.8256825Z waiting for server to shut down....2025-08-19 16:05:11.838 UTC [48] LOG:  aborting any active transactions
2025-08-19T16:07:48.8257548Z 2025-08-19 16:05:11.840 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
2025-08-19T16:07:48.8258076Z 2025-08-19 16:05:11.840 UTC [49] LOG:  shutting down
2025-08-19T16:07:48.8258512Z 2025-08-19 16:05:11.841 UTC [49] LOG:  checkpoint starting: shutdown immediate
2025-08-19T16:07:48.8259597Z 2025-08-19 16:05:11.857 UTC [49] LOG:  checkpoint complete: wrote 922 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.014 s, sync=0.003 s, total=0.017 s; sync files=301, longest=0.001 s, average=0.001 s; distance=4239 kB, estimate=4239 kB
2025-08-19T16:07:48.8260481Z 2025-08-19 16:05:11.864 UTC [48] LOG:  database system is shut down
2025-08-19T16:07:48.8260773Z  done
2025-08-19T16:07:48.8260941Z server stopped
2025-08-19T16:07:48.8261061Z 
2025-08-19T16:07:48.8261252Z PostgreSQL init process complete; ready for start up.
2025-08-19T16:07:48.8261468Z 
2025-08-19T16:07:48.8261766Z ##[endgroup]
